// src/data/locations.ts

export interface City {
	name: string;
	image: string;
	locations: number;
	courts: number;
	games: number;
}

export interface Country {
	name: string;
	image: string;
	locations: number;
	courts: number;
	games: number;
	cities: City[];
}

export const countryData: Country[] = [
	{
		name: 'United States',
		image: '/countries/united-states-flag.png',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{
				name: 'New York',
				image: '/cities/us-new-york.png',
				locations: 112,
				courts: 487,
				games: 923,
			},
			{
				name: 'Los Angeles',
				image: '/cities/us-los-angeles.png',
				locations: 89,
				courts: 392,
				games: 671,
			},
			{
				name: 'Chicago',
				image: '/cities/us-chicago.png',
				locations: 72,
				courts: 335,
				games: 204,
			},
			{
				name: 'Houston',
				image: '/cities/us-houston.png',
				locations: 94,
				courts: 413,
				games: 885,
			},
			{
				name: 'Phoenix',
				image: '/cities/us-phoenix.png',
				locations: 65,
				courts: 240,
				games: 512,
			},
			{
				name: 'Philadelphia',
				image: '/cities/us-philadelphia.png',
				locations: 61,
				courts: 230,
				games: 498,
			},
			{
				name: 'San Diego',
				image: '/cities/us-san-diego.png',
				locations: 58,
				courts: 218,
				games: 445,
			},
			{
				name: 'Dallas',
				image: '/cities/us-dallas.png',
				locations: 57,
				courts: 215,
				games: 432,
			},
			{
				name: 'Austin',
				image: '/cities/us-austin.png',
				locations: 47,
				courts: 189,
				games: 312,
			},
			{
				name: 'Jacksonville',
				image: '/cities/us-jacksonville.png',
				locations: 42,
				courts: 172,
				games: 298,
			},
			{
				name: 'San Francisco',
				image: '/cities/us-san-francisco.png',
				locations: 40,
				courts: 160,
				games: 320,
			},
			{
				name: 'Columbus',
				image: '/cities/us-columbus.png',
				locations: 38,
				courts: 152,
				games: 304,
			},
			{
				name: 'Fort Worth',
				image: '/cities/us-fort-worth.png',
				locations: 36,
				courts: 144,
				games: 288,
			},
			{
				name: 'Indianapolis',
				image: '/cities/us-indianapolis.png',
				locations: 34,
				courts: 136,
				games: 272,
			},
			{
				name: 'Charlotte',
				image: '/cities/us-charlotte.png',
				locations: 32,
				courts: 128,
				games: 256,
			},
			{
				name: 'Seattle',
				image: '/cities/us-seattle.png',
				locations: 63,
				courts: 251,
				games: 352,
			},
			{
				name: 'Denver',
				image: '/cities/us-denver.png',
				locations: 30,
				courts: 120,
				games: 240,
			},
			{
				name: 'Washington',
				image: '/cities/us-washington.png',
				locations: 28,
				courts: 112,
				games: 224,
			},
			{
				name: 'Boston',
				image: '/cities/us-boston.png',
				locations: 54,
				courts: 223,
				games: 398,
			},
			{
				name: 'El Paso',
				image: '/cities/us-el-paso.png',
				locations: 26,
				courts: 104,
				games: 208,
			},
			{
				name: 'Detroit',
				image: '/cities/us-detroit.png',
				locations: 24,
				courts: 96,
				games: 192,
			},
			{
				name: 'Nashville',
				image: '/cities/us-nashville.png',
				locations: 22,
				courts: 88,
				games: 176,
			},
			{
				name: 'Memphis',
				image: '/cities/us-memphis.png',
				locations: 20,
				courts: 80,
				games: 160,
			},
			{
				name: 'Portland',
				image: '/cities/us-portland.png',
				locations: 18,
				courts: 72,
				games: 144,
			},
			{
				name: 'Oklahoma City',
				image: '/cities/us-oklahoma-city.png',
				locations: 16,
				courts: 64,
				games: 128,
			},
			{
				name: 'Las Vegas',
				image: '/cities/us-las-vegas.png',
				locations: 14,
				courts: 56,
				games: 112,
			},
		],
	},
	{
		name: 'Canada',
		image: '/countries/canada-flag.png',
		locations: 2000,
		courts: 8000,
		games: 16000,
		cities: [
			{
				name: 'Toronto',
				image: '/cities/ca-toronto.png',
				locations: 82,
				courts: 260,
				games: 551,
			},
			{
				name: 'Vancouver',
				image: '/cities/ca-vancouver.png',
				locations: 67,
				courts: 245,
				games: 489,
			},
			{
				name: 'Montreal',
				image: '/cities/ca-montreal.png',
				locations: 54,
				courts: 198,
				games: 412,
			},
			{
				name: 'Calgary',
				image: '/cities/ca-calgary.png',
				locations: 43,
				courts: 176,
				games: 356,
			},
			{
				name: 'Ottawa',
				image: '/cities/ca-ottawa.png',
				locations: 35,
				courts: 141,
				games: 314,
			},
			{
				name: 'Edmonton',
				image: '/cities/ca-edmonton.png',
				locations: 30,
				courts: 128,
				games: 295,
			},
			{
				name: 'Winnipeg',
				image: '/cities/ca-winnipeg.png',
				locations: 28,
				courts: 112,
				games: 224,
			},
			{
				name: 'Quebec City',
				image: '/cities/ca-quebec-city.png',
				locations: 26,
				courts: 104,
				games: 208,
			},
			{
				name: 'Hamilton',
				image: '/cities/ca-hamilton.png',
				locations: 24,
				courts: 96,
				games: 192,
			},
			{
				name: 'Kitchener',
				image: '/cities/ca-kitchener.png',
				locations: 22,
				courts: 88,
				games: 176,
			},
		],
	},
	{
		name: 'United Kingdom',
		image: '/countries/uk-flag.png',
		locations: 1800,
		courts: 7200,
		games: 14500,
		cities: [
			{
				name: 'London',
				image: '/cities/uk-london.png',
				locations: 78,
				courts: 312,
				games: 654,
			},
			{
				name: 'Manchester',
				image: '/cities/uk-manchester.png',
				locations: 45,
				courts: 189,
				games: 398,
			},
			{
				name: 'Birmingham',
				image: '/cities/uk-birmingham.png',
				locations: 38,
				courts: 156,
				games: 287,
			},
			{
				name: 'Edinburgh',
				image: '/cities/uk-edinburgh.png',
				locations: 26,
				courts: 134,
				games: 140,
			},
			{
				name: 'Glasgow',
				image: '/cities/uk-glasgow.png',
				locations: 24,
				courts: 128,
				games: 165,
			},
			{
				name: 'Leeds',
				image: '/cities/uk-leeds.png',
				locations: 22,
				courts: 112,
				games: 210,
			},
			{
				name: 'Bristol',
				image: '/cities/uk-bristol.png',
				locations: 20,
				courts: 100,
				games: 180,
			},
			{
				name: 'Sheffield',
				image: '/cities/uk-sheffield.png',
				locations: 18,
				courts: 90,
				games: 162,
			},
			{
				name: 'Liverpool',
				image: '/cities/uk-liverpool.png',
				locations: 16,
				courts: 80,
				games: 144,
			},
		],
	},
	{
		name: 'Australia',
		image: '/countries/australia-flag.png',
		locations: 1700,
		courts: 6800,
		games: 13800,
		cities: [
			{
				name: 'Sydney',
				image: '/cities/au-sydney.png',
				locations: 58,
				courts: 234,
				games: 456,
			},
			{
				name: 'Melbourne',
				image: '/cities/au-melbourne.png',
				locations: 52,
				courts: 212,
				games: 389,
			},
			{
				name: 'Brisbane',
				image: '/cities/au-brisbane.png',
				locations: 28,
				courts: 112,
				games: 167,
			},
			{
				name: 'Perth',
				image: '/cities/au-perth.png',
				locations: 18,
				courts: 65,
				games: 77,
			},
			{
				name: 'Adelaide',
				image: '/cities/au-adelaide.png',
				locations: 16,
				courts: 72,
				games: 95,
			},
			{
				name: 'Gold Coast',
				image: '/cities/au-gold-coast.png',
				locations: 14,
				courts: 56,
				games: 112,
			},
			{
				name: 'Canberra',
				image: '/cities/au-canberra.png',
				locations: 12,
				courts: 48,
				games: 96,
			},
			{
				name: 'Newcastle',
				image: '/cities/au-newcastle.png',
				locations: 10,
				courts: 40,
				games: 80,
			},
		],
	},
	{
		name: 'India',
		image: '/countries/india-flag.png',
		locations: 900,
		courts: 3600,
		games: 7200,
		cities: [
			{
				name: 'Chennai',
				image: '/cities/in-chennai.png',
				locations: 76,
				courts: 144,
				games: 428,
			},
			{
				name: 'Mumbai',
				image: '/cities/in-mumbai.png',
				locations: 58,
				courts: 232,
				games: 387,
			},
			{
				name: 'Bangalore',
				image: '/cities/in-bangalore.png',
				locations: 52,
				courts: 289,
				games: 321,
			},
			{
				name: 'New Delhi',
				image: '/cities/in-new-delhi.png',
				locations: 33,
				courts: 201,
				games: 209,
			},
			{
				name: 'Hyderabad',
				image: '/cities/in-hyderabad.png',
				locations: 22,
				courts: 116,
				games: 178,
			},
			{
				name: 'Pune',
				image: '/cities/in-pune.png',
				locations: 20,
				courts: 100,
				games: 160,
			},
			{
				name: 'Kolkata',
				image: '/cities/in-kolkata.png',
				locations: 18,
				courts: 90,
				games: 144,
			},
			{
				name: 'Ahmedabad',
				image: '/cities/in-ahmedabad.png',
				locations: 16,
				courts: 80,
				games: 128,
			},
		],
	},
	{
		name: 'Philippines',
		image: '/countries/philippines-flag.png',
		locations: 600,
		courts: 2400,
		games: 4800,
		cities: [
			{
				name: 'Manila',
				image: '/cities/ph-manila.png',
				locations: 34,
				courts: 142,
				games: 287,
			},
			{
				name: 'Mandaluyong',
				image: '/cities/ph-mandaluyong.png',
				locations: 18,
				courts: 76,
				games: 156,
			},
			{
				name: 'Quezon City',
				image: '/cities/ph-quezon-city.png',
				locations: 22,
				courts: 89,
				games: 134,
			},
			{
				name: 'Makati',
				image: '/cities/ph-makati.png',
				locations: 15,
				courts: 59,
				games: 68,
			},
			{
				name: 'BGC',
				image: '/cities/ph-bgc.png',
				locations: 12,
				courts: 48,
				games: 95,
			},
			{
				name: 'Cebu City',
				image: '/cities/ph-cebu-city.png',
				locations: 12,
				courts: 48,
				games: 95,
			},
			{
				name: 'Davao City',
				image: '/cities/ph-davao-city.png',
				locations: 10,
				courts: 40,
				games: 80,
			},
			{
				name: 'Iloilo City',
				image: '/cities/ph-iloilo-city.png',
				locations: 8,
				courts: 32,
				games: 64,
			},
		],
	},
	{
		name: 'Spain',
		image: '/countries/spain-flag.png',
		locations: 750,
		courts: 3000,
		games: 6100,
		cities: [
			{
				name: 'Madrid',
				image: '/cities/es-madrid.png',
				locations: 40,
				courts: 160,
				games: 320,
			},
			{
				name: 'Barcelona',
				image: '/cities/es-barcelona.png',
				locations: 38,
				courts: 152,
				games: 304,
			},
			{
				name: 'Valencia',
				image: '/cities/es-valencia.png',
				locations: 20,
				courts: 80,
				games: 160,
			},
			{
				name: 'Seville',
				image: '/cities/es-seville.png',
				locations: 18,
				courts: 72,
				games: 144,
			},
			{
				name: 'Malaga',
				image: '/cities/es-malaga.png',
				locations: 16,
				courts: 64,
				games: 128,
			},
		],
	},
	{
		name: 'Mexico',
		image: '/countries/mexico-flag.png',
		locations: 680,
		courts: 2720,
		games: 5500,
		cities: [
			{
				name: 'Mexico City',
				image: '/cities/mx-mexico-city.png',
				locations: 50,
				courts: 200,
				games: 400,
			},
			{
				name: 'Guadalajara',
				image: '/cities/mx-guadalajara.png',
				locations: 30,
				courts: 120,
				games: 240,
			},
			{
				name: 'Monterrey',
				image: '/cities/mx-monterrey.png',
				locations: 25,
				courts: 100,
				games: 200,
			},
			{
				name: 'Tijuana',
				image: '/cities/mx-tijuana.png',
				locations: 20,
				courts: 80,
				games: 160,
			},
		],
	},
	{
		name: 'Singapore',
		image: '/countries/singapore-flag.png',
		locations: 500,
		courts: 2000,
		games: 4200,
		cities: [
			{
				name: 'Singapore',
				image: '/cities/sg-singapore.png',
				locations: 120,
				courts: 480,
				games: 960,
			},
			{
				name: 'Jurong',
				image: '/cities/sg-jurong.png',
				locations: 40,
				courts: 160,
				games: 320,
			},
			{
				name: 'Woodlands',
				image: '/cities/sg-woodlands.png',
				locations: 30,
				courts: 120,
				games: 240,
			},
		],
	},
	{
		name: 'Malaysia',
		image: '/countries/malaysia-flag.png',
		locations: 450,
		courts: 1800,
		games: 3700,
		cities: [
			{
				name: 'Kuala Lumpur',
				image: '/cities/my-kuala-lumpur.png',
				locations: 85,
				courts: 340,
				games: 680,
			},
			{
				name: 'George Town',
				image: '/cities/my-george-town.png',
				locations: 30,
				courts: 120,
				games: 240,
			},
			{
				name: 'Johor Bahru',
				image: '/cities/my-johor-bahru.png',
				locations: 25,
				courts: 100,
				games: 200,
			},
			{
				name: 'Kota Kinabalu',
				image: '/cities/my-kota-kinabalu.png',
				locations: 20,
				courts: 80,
				games: 160,
			},
		],
	},
	{
		name: 'Vietnam',
		image: '/countries/vietnam-flag.png',
		locations: 400,
		courts: 1600,
		games: 3400,
		cities: [
			{
				name: 'Ho Chi Minh City',
				image: '/cities/vn-ho-chi-minh.png',
				locations: 70,
				courts: 280,
				games: 560,
			},
			{
				name: 'Hanoi',
				image: '/cities/vn-hanoi.png',
				locations: 65,
				courts: 260,
				games: 520,
			},
			{
				name: 'Da Nang',
				image: '/cities/vn-da-nang.png',
				locations: 30,
				courts: 120,
				games: 240,
			},
			{
				name: 'Can Tho',
				image: '/cities/vn-can-tho.png',
				locations: 20,
				courts: 80,
				games: 160,
			},
		],
	},
	{
		name: 'Thailand',
		image: '/countries/thailand-flag.png',
		locations: 180,
		courts: 450,
		games: 1200,
		cities: [
			{
				name: 'Bangkok',
				image: '/cities/th-bangkok.png',
				locations: 65,
				courts: 180,
				games: 450,
			},
			{
				name: 'Chiang Mai',
				image: '/cities/th-chiang-mai.png',
				locations: 32,
				courts: 85,
				games: 240,
			},
			{
				name: 'Phuket',
				image: '/cities/th-phuket.png',
				locations: 28,
				courts: 75,
				games: 210,
			},
			{
				name: 'Pattaya',
				image: '/cities/th-pattaya.png',
				locations: 25,
				courts: 55,
				games: 150,
			},
			{
				name: 'Hua Hin',
				image: '/cities/th-hua-hin.png',
				locations: 18,
				courts: 35,
				games: 90,
			},
			{
				name: 'Koh Samui',
				image: '/cities/th-koh-samui.png',
				locations: 12,
				courts: 20,
				games: 60,
			},
		],
	},
];
