export const stateData = [
	// Alabama
	{
		name: 'Alabama',
		country: 'United States',
		image: '/alabama-birmingham-skyline.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Birmingham', image: '/cities/al-birmingham.png' },
			{ name: 'Mobile', image: '/cities/al-mobile.png' },
			{ name: 'Huntsville', image: '/cities/al-huntsville.png' },
			{ name: 'Montgomery', image: '/cities/al-montgomery.png' },
			{ name: 'Tuscaloosa', image: '/cities/al-tuscaloosa.png' },
		],
	},
	// Alaska
	{
		name: 'Alaska',
		country: 'United States',
		image: '/alaska-anchorage-landscape.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Anchorage', image: '/cities/ak-anchorage.png' },
			{ name: 'Juneau', image: '/cities/ak-juneau.png' },
			{ name: 'Fairbanks', image: '/cities/ak-fairbanks.png' },
			{ name: 'Wasilla', image: '/cities/ak-wasilla.png' },
			{ name: 'Ketchikan', image: '/cities/ak-ketchikan.png' },
		],
	},
	// Arizona
	{
		name: 'Arizona',
		country: 'United States',
		image: '/arizona-desert-cactus.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Phoenix', image: '/cities/az-phoenix.png' },
			{ name: 'Scottsdale', image: '/cities/az-scottsdale.png' },
			{ name: 'Tucson', image: '/cities/az-tucson.png' },
			{ name: 'Mesa', image: '/cities/az-mesa.png' },
			{ name: 'Tempe', image: '/cities/az-tempe.png' },
		],
	},
	// Arkansas
	{
		name: 'Arkansas',
		country: 'United States',
		image: '/arkansas-little-rock-river.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Little Rock', image: '/cities/ar-little-rock.png' },
			{ name: 'Fayetteville', image: '/cities/ar-fayetteville.png' },
			{ name: 'Hot Springs', image: '/cities/ar-hot-springs.png' },
			{ name: 'Bentonville', image: '/cities/ar-bentonville.png' },
			{ name: 'Jonesboro', image: '/cities/ar-jonesboro.png' },
		],
	},
	// California
	{
		name: 'California',
		country: 'United States',
		image: '/california-golden-gate-bridge-scenic-view.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Los Angeles', image: '/cities/us-la.png' },
			{ name: 'San Diego', image: '/cities/us-san-diego.png' },
			{ name: 'San Francisco', image: '/cities/us-san-francisco.png' },
			{ name: 'Sacramento', image: '/cities/us-sacramento.png' },
			{ name: 'Palm Springs', image: '/cities/us-palm-springs.png' },
			{ name: 'Oakland', image: '/cities/us-oakland.png' },
			{ name: 'Fresno', image: '/cities/us-fresno.png' },
			{ name: 'San Jose', image: '/cities/us-san-jose.png' },
			{ name: 'Irvine', image: '/cities/us-irvine.png' },
		],
	},
	// Colorado
	{
		name: 'Colorado',
		country: 'United States',
		image: '/colorado-mountains-denver.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Denver', image: '/cities/co-denver.png' },
			{ name: 'Boulder', image: '/cities/co-boulder.png' },
			{ name: 'Colorado Springs', image: '/cities/co-colorado-springs.png' },
			{ name: 'Fort Collins', image: '/cities/co-fort-collins.png' },
			{ name: 'Aurora', image: '/cities/co-aurora.png' },
		],
	},
	// Connecticut
	{
		name: 'Connecticut',
		country: 'United States',
		image: '/connecticut-hartford-river.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Hartford', image: '/cities/ct-hartford.png' },
			{ name: 'Bridgeport', image: '/cities/ct-bridgeport.png' },
			{ name: 'New Haven', image: '/cities/ct-new-haven.png' },
			{ name: 'Stamford', image: '/cities/ct-stamford.png' },
			{ name: 'Norwalk', image: '/cities/ct-norwalk.png' },
		],
	},
	// Delaware
	{
		name: 'Delaware',
		country: 'United States',
		image: '/delaware-wilmington-river.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Wilmington', image: '/cities/de-wilmington.png' },
			{ name: 'Dover', image: '/cities/de-dover.png' },
			{ name: 'Newark', image: '/cities/de-newark.png' },
			{ name: 'Middletown', image: '/cities/de-middletown.png' },
			{ name: 'Rehoboth Beach', image: '/cities/de-rehoboth-beach.png' },
		],
	},
	// Florida
	{
		name: 'Florida',
		country: 'United States',
		image: '/florida-beach-palm-trees-sunset.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Miami', image: '/cities/us-miami.png' },
			{ name: 'Orlando', image: '/cities/us-orlando.png' },
			{ name: 'Tampa', image: '/cities/us-tampa.png' },
			{ name: 'Jacksonville', image: '/cities/us-jacksonville.png' },
			{ name: 'Fort Lauderdale', image: '/cities/us-fort-lauderdale.png' },
			{ name: 'St Petersburg', image: '/cities/us-stpetersburg.png' },
			{ name: 'Naples', image: '/cities/us-naples.png' },
			{ name: 'Sarasota', image: '/cities/us-sarasota.png' },
			{ name: 'West Palm Beach', image: '/cities/us-west-palm-beach.png' },
		],
	},
	// Georgia
	{
		name: 'Georgia',
		country: 'United States',
		image: '/georgia-atlanta-skyline.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Atlanta', image: '/cities/ga-atlanta.png' },
			{ name: 'Savannah', image: '/cities/ga-savannah.png' },
			{ name: 'Augusta', image: '/cities/ga-augusta.png' },
			{ name: 'Athens', image: '/cities/ga-athens.png' },
			{ name: 'Macon', image: '/cities/ga-macon.png' },
		],
	},
	// Hawaii
	{
		name: 'Hawaii',
		country: 'United States',
		image: '/hawaii-honolulu-beach.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Honolulu', image: '/cities/hi-honolulu.png' },
			{ name: 'Maui', image: '/cities/hi-maui.png' },
			{ name: 'Hilo', image: '/cities/hi-hilo.png' },
			{ name: 'Kailua', image: '/cities/hi-kailua.png' },
			{ name: 'Kona', image: '/cities/hi-kona.png' },
		],
	},
	// Idaho
	{
		name: 'Idaho',
		country: 'United States',
		image: '/idaho-boise-mountains.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Boise', image: '/cities/id-boise.png' },
			{ name: 'Coeur dAlene', image: '/cities/id-coeur-dalene.png' },
			{ name: 'Idaho Falls', image: '/cities/id-idaho-falls.png' },
			{ name: 'Nampa', image: '/cities/id-nampa.png' },
			{ name: 'Meridian', image: '/cities/id-meridian.png' },
		],
	},
	// Illinois
	{
		name: 'Illinois',
		country: 'United States',
		image: '/illinois-chicago-architecture.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Chicago', image: '/cities/us-chicago.png' },
			{ name: 'Naperville', image: '/cities/us-naperville.png' },
			{ name: 'Rockford', image: '/cities/us-rockford.png' },
			{ name: 'Springfield', image: '/cities/us-springfield.png' },
			{ name: 'Peoria', image: '/cities/us-peoria.png' },
		],
	},
	// Indiana
	{
		name: 'Indiana',
		country: 'United States',
		image: '/indiana-indianapolis-monument.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Indianapolis', image: '/cities/in-indianapolis.png' },
			{ name: 'Fort Wayne', image: '/cities/in-fort-wayne.png' },
			{ name: 'Bloomington', image: '/cities/in-bloomington.png' },
			{ name: 'Evansville', image: '/cities/in-evansville.png' },
			{ name: 'South Bend', image: '/cities/in-south-bend.png' },
		],
	},
	// Iowa
	{
		name: 'Iowa',
		country: 'United States',
		image: '/iowa-des-moines-skyline.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Des Moines', image: '/cities/ia-des-moines.png' },
			{ name: 'Cedar Rapids', image: '/cities/ia-cedar-rapids.png' },
			{ name: 'Davenport', image: '/cities/ia-davenport.png' },
			{ name: 'Sioux City', image: '/cities/ia-sioux-city.png' },
			{ name: 'Iowa City', image: '/cities/ia-iowa-city.png' },
		],
	},
	// Kansas
	{
		name: 'Kansas',
		country: 'United States',
		image: '/kansas-wichita-plains.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Wichita', image: '/cities/ks-wichita.png' },
			{ name: 'Kansas City', image: '/cities/ks-kansas-city.png' },
			{ name: 'Overland Park', image: '/cities/ks-overland-park.png' },
			{ name: 'Topeka', image: '/cities/ks-topeka.png' },
			{ name: 'Lawrence', image: '/cities/ks-lawrence.png' },
		],
	},
	// Kentucky
	{
		name: 'Kentucky',
		country: 'United States',
		image: '/kentucky-louisville-bridge.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Louisville', image: '/cities/ky-louisville.png' },
			{ name: 'Lexington', image: '/cities/ky-lexington.png' },
			{ name: 'Bowling Green', image: '/cities/ky-bowling-green.png' },
			{ name: 'Owensboro', image: '/cities/ky-owensboro.png' },
			{ name: 'Covington', image: '/cities/ky-covington.png' },
		],
	},
	// Louisiana
	{
		name: 'Louisiana',
		country: 'United States',
		image: '/louisiana-new-orleans-mississippi-river.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'New Orleans', image: '/cities/la-new-orleans.png' },
			{ name: 'Baton Rouge', image: '/cities/la-baton-rouge.png' },
			{ name: 'Lafayette', image: '/cities/la-lafayette.png' },
			{ name: 'Shreveport', image: '/cities/la-shreveport.png' },
			{ name: 'Metairie', image: '/cities/la-metairie.png' },
		],
	},
	// Maine
	{
		name: 'Maine',
		country: 'United States',
		image: '/maine-portland-coastline.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Portland', image: '/cities/me-portland.png' },
			{ name: 'Bangor', image: '/cities/me-bangor.png' },
			{ name: 'Lewiston', image: '/cities/me-lewiston.png' },
			{ name: 'Augusta', image: '/cities/me-augusta.png' },
			{ name: 'Auburn', image: '/cities/me-auburn.png' },
		],
	},
	// Maryland
	{
		name: 'Maryland',
		country: 'United States',
		image: '/maryland-baltimore-inner-harbor.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Baltimore', image: '/cities/md-baltimore.png' },
			{ name: 'Annapolis', image: '/cities/md-annapolis.png' },
			{ name: 'Frederick', image: '/cities/md-frederick.png' },
			{ name: 'Rockville', image: '/cities/md-rockville.png' },
			{ name: 'Gaithersburg', image: '/cities/md-gaithersburg.png' },
		],
	},
	// Massachusetts
	{
		name: 'Massachusetts',
		country: 'United States',
		image: '/massachusetts-boston-harbor-autumn.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Boston', image: '/cities/us-boston.png' },
			{ name: 'Worcester', image: '/cities/us-worcester.png' },
			{ name: 'Springfield', image: '/cities/us-springfield-ma.png' },
			{ name: 'Cambridge', image: '/cities/us-cambridge.png' },
			{ name: 'Lowell', image: '/cities/us-lowell.png' },
		],
	},
	// Michigan
	{
		name: 'Michigan',
		country: 'United States',
		image: '/michigan-detroit-skyline.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Detroit', image: '/cities/mi-detroit.png' },
			{ name: 'Grand Rapids', image: '/cities/mi-grand-rapids.png' },
			{ name: 'Ann Arbor', image: '/cities/mi-ann-arbor.png' },
			{ name: 'Traverse City', image: '/cities/mi-traverse-city.png' },
			{ name: 'Lansing', image: '/cities/mi-lansing.png' },
		],
	},
	// Minnesota
	{
		name: 'Minnesota',
		country: 'United States',
		image: '/minnesota-minneapolis-lakes.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Minneapolis', image: '/cities/mn-minneapolis.png' },
			{ name: 'St Paul', image: '/cities/mn-st-paul.png' },
			{ name: 'Rochester', image: '/cities/mn-rochester.png' },
			{ name: 'Duluth', image: '/cities/mn-duluth.png' },
			{ name: 'Bloomington', image: '/cities/mn-bloomington.png' },
		],
	},
	// Mississippi
	{
		name: 'Mississippi',
		country: 'United States',
		image: '/mississippi-jackson-capitol.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Jackson', image: '/cities/ms-jackson.png' },
			{ name: 'Gulfport', image: '/cities/ms-gulfport.png' },
			{ name: 'Biloxi', image: '/cities/ms-biloxi.png' },
			{ name: 'Hattiesburg', image: '/cities/ms-hattiesburg.png' },
			{ name: 'Tupelo', image: '/cities/ms-tupelo.png' },
		],
	},
	// Missouri
	{
		name: 'Missouri',
		country: 'United States',
		image: '/missouri-st-louis-arch.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'St Louis', image: '/cities/mo-st-louis.png' },
			{ name: 'Kansas City', image: '/cities/mo-kansas-city.png' },
			{ name: 'Springfield', image: '/cities/mo-springfield.png' },
			{ name: 'Columbia', image: '/cities/mo-columbia.png' },
			{ name: 'Branson', image: '/cities/mo-branson.png' },
		],
	},
	// Montana
	{
		name: 'Montana',
		country: 'United States',
		image: '/montana-glacier-national-park.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Billings', image: '/cities/mt-billings.png' },
			{ name: 'Missoula', image: '/cities/mt-missoula.png' },
			{ name: 'Bozeman', image: '/cities/mt-bozeman.png' },
			{ name: 'Helena', image: '/cities/mt-helena.png' },
			{ name: 'Great Falls', image: '/cities/mt-great-falls.png' },
		],
	},
	// Nebraska
	{
		name: 'Nebraska',
		country: 'United States',
		image: '/nebraska-omaha-downtown.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Omaha', image: '/cities/ne-omaha.png' },
			{ name: 'Lincoln', image: '/cities/ne-lincoln.png' },
			{ name: 'Bellevue', image: '/cities/ne-bellevue.png' },
			{ name: 'Grand Island', image: '/cities/ne-grand-island.png' },
			{ name: 'Kearney', image: '/cities/ne-kearney.png' },
		],
	},
	// Nevada
	{
		name: 'Nevada',
		country: 'United States',
		image: '/nevada-las-vegas-strip.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Las Vegas', image: '/cities/nv-las-vegas.png' },
			{ name: 'Reno', image: '/cities/nv-reno.png' },
			{ name: 'Henderson', image: '/cities/nv-henderson.png' },
			{ name: 'Carson City', image: '/cities/nv-carson-city.png' },
			{ name: 'Lake Tahoe', image: '/cities/nv-lake-tahoe.png' },
		],
	},
	// New Hampshire
	{
		name: 'New Hampshire',
		country: 'United States',
		image: '/new-hampshire-white-mountains.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Manchester', image: '/cities/nh-manchester.png' },
			{ name: 'Nashua', image: '/cities/nh-nashua.png' },
			{ name: 'Concord', image: '/cities/nh-concord.png' },
			{ name: 'Portsmouth', image: '/cities/nh-portsmouth.png' },
			{ name: 'Hanover', image: '/cities/nh-hanover.png' },
		],
	},
	// New Jersey
	{
		name: 'New Jersey',
		country: 'United States',
		image: '/new-jersey-atlantic-city-boardwalk.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Newark', image: '/cities/nj-newark.png' },
			{ name: 'Jersey City', image: '/cities/nj-jersey-city.png' },
			{ name: 'Atlantic City', image: '/cities/nj-atlantic-city.png' },
			{ name: 'Princeton', image: '/cities/nj-princeton.png' },
			{ name: 'Trenton', image: '/cities/nj-trenton.png' },
		],
	},
	// New Mexico
	{
		name: 'New Mexico',
		country: 'United States',
		image: '/new-mexico-santa-fe-adobe.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Albuquerque', image: '/cities/nm-albuquerque.png' },
			{ name: 'Santa Fe', image: '/cities/nm-santa-fe.png' },
			{ name: 'Las Cruces', image: '/cities/nm-las-cruces.png' },
			{ name: 'Taos', image: '/cities/nm-taos.png' },
			{ name: 'Roswell', image: '/cities/nm-roswell.png' },
		],
	},
	// New York
	{
		name: 'New York',
		country: 'United States',
		image: '/new-york-manhattan-skyline.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'New York City', image: '/cities/us-nyc.png' },
			{ name: 'Buffalo', image: '/cities/us-buffalo.png' },
			{ name: 'Rochester', image: '/cities/us-rochester.png' },
			{ name: 'Albany', image: '/cities/us-albany.png' },
			{ name: 'Syracuse', image: '/cities/us-syracuse.png' },
		],
	},
	// North Carolina
	{
		name: 'North Carolina',
		country: 'United States',
		image: '/north-carolina-charlotte-skyline.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Charlotte', image: '/cities/nc-charlotte.png' },
			{ name: 'Raleigh', image: '/cities/nc-raleigh.png' },
			{ name: 'Asheville', image: '/cities/nc-asheville.png' },
			{ name: 'Durham', image: '/cities/nc-durham.png' },
			{ name: 'Wilmington', image: '/cities/nc-wilmington.png' },
		],
	},
	// North Dakota
	{
		name: 'North Dakota',
		country: 'United States',
		image: '/north-dakota-fargo-plains.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Fargo', image: '/cities/nd-fargo.png' },
			{ name: 'Bismarck', image: '/cities/nd-bismarck.png' },
			{ name: 'Grand Forks', image: '/cities/nd-grand-forks.png' },
			{ name: 'Minot', image: '/cities/nd-minot.png' },
			{ name: 'Dickinson', image: '/cities/nd-dickinson.png' },
		],
	},
	// Ohio
	{
		name: 'Ohio',
		country: 'United States',
		image: '/ohio-cleveland-lakefront.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Columbus', image: '/cities/oh-columbus.png' },
			{ name: 'Cleveland', image: '/cities/oh-cleveland.png' },
			{ name: 'Cincinnati', image: '/cities/oh-cincinnati.png' },
			{ name: 'Toledo', image: '/cities/oh-toledo.png' },
			{ name: 'Akron', image: '/cities/oh-akron.png' },
		],
	},
	// Oklahoma
	{
		name: 'Oklahoma',
		country: 'United States',
		image: '/oklahoma-oklahoma-city-downtown.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Oklahoma City', image: '/cities/ok-oklahoma-city.png' },
			{ name: 'Tulsa', image: '/cities/ok-tulsa.png' },
			{ name: 'Norman', image: '/cities/ok-norman.png' },
			{ name: 'Broken Arrow', image: '/cities/ok-broken-arrow.png' },
			{ name: 'Edmond', image: '/cities/ok-edmond.png' },
		],
	},
	// Oregon
	{
		name: 'Oregon',
		country: 'United States',
		image: '/oregon-portland-mount-hood.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Portland', image: '/cities/or-portland.png' },
			{ name: 'Eugene', image: '/cities/or-eugene.png' },
			{ name: 'Bend', image: '/cities/or-bend.png' },
			{ name: 'Salem', image: '/cities/or-salem.png' },
			{ name: 'Crater Lake', image: '/cities/or-crater-lake.png' },
		],
	},
	// Pennsylvania
	{
		name: 'Pennsylvania',
		country: 'United States',
		image: '/pennsylvania-philadelphia-skyline.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Philadelphia', image: '/cities/us-philadelphia.png' },
			{ name: 'Pittsburgh', image: '/cities/us-pittsburgh.png' },
			{ name: 'Lancaster', image: '/cities/us-lancaster.png' },
			{ name: 'Harrisburg', image: '/cities/us-harrisburg.png' },
			{ name: 'Allentown', image: '/cities/us-allentown.png' },
		],
	},
	// Rhode Island
	{
		name: 'Rhode Island',
		country: 'United States',
		image: '/rhode-island-newport-mansions.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Providence', image: '/cities/ri-providence.png' },
			{ name: 'Newport', image: '/cities/ri-newport.png' },
			{ name: 'Warwick', image: '/cities/ri-warwick.png' },
			{ name: 'Cranston', image: '/cities/ri-cranston.png' },
			{ name: 'Pawtucket', image: '/cities/ri-pawtucket.png' },
		],
	},
	// South Carolina
	{
		name: 'South Carolina',
		country: 'United States',
		image: '/south-carolina-charleston-waterfront.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Charleston', image: '/cities/sc-charleston.png' },
			{ name: 'Columbia', image: '/cities/sc-columbia.png' },
			{ name: 'Myrtle Beach', image: '/cities/sc-myrtle-beach.png' },
			{ name: 'Greenville', image: '/cities/sc-greenville.png' },
			{ name: 'Hilton Head', image: '/cities/sc-hilton-head.png' },
		],
	},
	// South Dakota
	{
		name: 'South Dakota',
		country: 'United States',
		image: '/south-dakota-mount-rushmore.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Sioux Falls', image: '/cities/sd-sioux-falls.png' },
			{ name: 'Rapid City', image: '/cities/sd-rapid-city.png' },
			{ name: 'Aberdeen', image: '/cities/sd-aberdeen.png' },
			{ name: 'Brookings', image: '/cities/sd-brookings.png' },
			{ name: 'Deadwood', image: '/cities/sd-deadwood.png' },
		],
	},
	// Tennessee
	{
		name: 'Tennessee',
		country: 'United States',
		image: '/tennessee-nashville-skyline.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Nashville', image: '/cities/tn-nashville.png' },
			{ name: 'Memphis', image: '/cities/tn-memphis.png' },
			{ name: 'Knoxville', image: '/cities/tn-knoxville.png' },
			{ name: 'Chattanooga', image: '/cities/tn-chattanooga.png' },
			{ name: 'Gatlinburg', image: '/cities/tn-gatlinburg.png' },
		],
	},
	// Texas
	{
		name: 'Texas',
		country: 'United States',
		image: '/texas-austin-capitol.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Houston', image: '/cities/us-houston.png' },
			{ name: 'Dallas', image: '/cities/us-dallas.png' },
			{ name: 'Austin', image: '/cities/us-austin.png' },
			{ name: 'San Antonio', image: '/cities/us-san-antonio.png' },
			{ name: 'Fort Worth', image: '/cities/us-fort-worth.png' },
			{ name: 'El Paso', image: '/cities/us-el-paso.png' },
		],
	},
	// Utah
	{
		name: 'Utah',
		country: 'United States',
		image: '/utah-salt-lake-city-mountains.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Salt Lake City', image: '/cities/ut-salt-lake-city.png' },
			{ name: 'Park City', image: '/cities/ut-park-city.png' },
			{ name: 'Provo', image: '/cities/ut-provo.png' },
			{ name: 'Moab', image: '/cities/ut-moab.png' },
			{ name: 'St George', image: '/cities/ut-st-george.png' },
		],
	},
	// Vermont
	{
		name: 'Vermont',
		country: 'United States',
		image: '/vermont-burlington-lake-champlain.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Burlington', image: '/cities/vt-burlington.png' },
			{ name: 'Montpelier', image: '/cities/vt-montpelier.png' },
			{ name: 'Stowe', image: '/cities/vt-stowe.png' },
			{ name: 'Rutland', image: '/cities/vt-rutland.png' },
			{ name: 'Brattleboro', image: '/cities/vt-brattleboro.png' },
		],
	},
	// Virginia
	{
		name: 'Virginia',
		country: 'United States',
		image: '/virginia-richmond-capitol.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Virginia Beach', image: '/cities/va-virginia-beach.png' },
			{ name: 'Richmond', image: '/cities/va-richmond.png' },
			{ name: 'Arlington', image: '/cities/va-arlington.png' },
			{ name: 'Charlottesville', image: '/cities/va-charlottesville.png' },
			{ name: 'Alexandria', image: '/cities/va-alexandria.png' },
		],
	},
	// Washington
	{
		name: 'Washington',
		country: 'United States',
		image: '/washington-seattle-space-needle.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Seattle', image: '/cities/wa-seattle.png' },
			{ name: 'Spokane', image: '/cities/wa-spokane.png' },
			{ name: 'Tacoma', image: '/cities/wa-tacoma.png' },
			{ name: 'Bellevue', image: '/cities/wa-bellevue.png' },
			{ name: 'Olympia', image: '/cities/wa-olympia.png' },
		],
	},
	// West Virginia
	{
		name: 'West Virginia',
		country: 'United States',
		image: '/west-virginia-charleston-capitol.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Charleston', image: '/cities/wv-charleston.png' },
			{ name: 'Huntington', image: '/cities/wv-huntington.png' },
			{ name: 'Morgantown', image: '/cities/wv-morgantown.png' },
			{ name: 'Wheeling', image: '/cities/wv-wheeling.png' },
			{ name: 'Parkersburg', image: '/cities/wv-parkersburg.png' },
		],
	},
	// Wisconsin
	{
		name: 'Wisconsin',
		country: 'United States',
		image: '/wisconsin-milwaukee-lakefront.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Milwaukee', image: '/cities/wi-milwaukee.png' },
			{ name: 'Madison', image: '/cities/wi-madison.png' },
			{ name: 'Green Bay', image: '/cities/wi-green-bay.png' },
			{ name: 'Door County', image: '/cities/wi-door-county.png' },
			{ name: 'Kenosha', image: '/cities/wi-kenosha.png' },
		],
	},
	// Wyoming
	{
		name: 'Wyoming',
		country: 'United States',
		image: '/wyoming-yellowstone-geysers.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'Cheyenne', image: '/cities/wy-cheyenne.png' },
			{ name: 'Jackson Hole', image: '/cities/wy-jackson-hole.png' },
			{ name: 'Casper', image: '/cities/wy-casper.png' },
			{ name: 'Laramie', image: '/cities/wy-laramie.png' },
			{ name: 'Cody', image: '/cities/wy-cody.png' },
		],
	},
	// Puerto Rico
	{
		name: 'Puerto Rico',
		country: 'United States',
		image: '/puerto-rico-san-juan-beach.jpg',
		locations: 15000,
		courts: 60000,
		games: 120000,
		cities: [
			{ name: 'San Juan', image: '/cities/pr-san-juan.png' },
			{ name: 'Ponce', image: '/cities/pr-ponce.png' },
			{ name: 'Mayagüez', image: '/cities/pr-mayaguez.png' },
			{ name: 'Bayamón', image: '/cities/pr-bayamon.png' },
			{ name: 'Carolina', image: '/cities/pr-carolina.png' },
		],
	},
];
