// PADDLE_DATABASE.ts

import { Paddle } from '../types';

// --- You can extend these paddles as new models and review cycles update ---

export const PADDLE_DATABASE: Record<
	'power' | 'control' | 'all-court' | 'beginner',
	Paddle[]
> = {
	'power': [
		{
			id: 'crbn-1x-power',
			name: 'CRBN 1X Power Series',
			brand: 'CRBN',
			price: 229.99,
			image: '/api/placeholder/300/200',
			weight: '7.8-8.3 oz',
			core_thickness: '13mm/14mm',
			surface: 'Raw T700 Carbon Fiber',
			shape: 'Elongated',
			handle_length: '5.5"',
			grip_circumference: '4.25"',
			power_rating: 9,
			control_rating: 7,
			spin_rating: 9,
			forgiveness_rating: 6,
			skill_level: ['intermediate', 'advanced'],
			description:
				'Tour-level power paddle with raw carbon face for explosive drives and spin. Features UNIBODY design for durability.',
			key_features: [
				'Raw carbon fiber face for maximum spin',
				'Elongated shape for reach and power',
				'Foam-injected edges for stability',
				'UNIBODY construction eliminates weak points',
			],
			best_for: [
				'Power baseline play',
				'Aggressive net finishing',
				'Tournament competition',
			],
			pros: [
				'Explosive power',
				'Excellent spin generation',
				'Durable construction',
				'Pro-level performance',
			],
			cons: [
				'Smaller sweet spot',
				'Less forgiving on mishits',
				'Premium price point',
			],
		},
		{
			id: 'joola-perseus-14mm',
			name: 'JOOLA Perseus Pro IV 14mm',
			brand: 'JOOLA',
			price: 199.95,
			image: '/api/placeholder/300/200',
			weight: '7.9-8.3 oz',
			core_thickness: '14mm',
			surface: 'Textured Carbon Fiber',
			shape: 'Elongated',
			handle_length: '5.5"',
			grip_circumference: '4.25"',
			power_rating: 10,
			control_rating: 7,
			spin_rating: 8,
			forgiveness_rating: 6,
			skill_level: ['advanced'],
			description:
				'Ben Johns signature paddle with explosive power. Features TechFlex Power technology for optimized energy transfer.',
			key_features: [
				'TechFlex Power (TFP) technology',
				'Propulsion core for explosive power',
				'Hyper-Foam edge wall',
				'Textured carbon surface for spin',
			],
			best_for: [
				'Aggressive baseline play',
				'Power finishing shots',
				'Tournament level competition',
			],
			pros: [
				'Maximum power output',
				'Pro-level performance',
				'Good spin capability',
				'Tour-proven design',
			],
			cons: [
				'Less forgiving',
				'Requires advanced technique',
				'Can overhit easily',
			],
		},
		{
			id: 'engage-pursuit-pro-mx',
			name: 'Engage Pursuit Pro MX',
			brand: 'Engage',
			price: 207.99,
			image: '/api/placeholder/300/200',
			weight: '7.8-8.2 oz',
			core_thickness: '12.7mm',
			surface: 'Raw T700 Carbon Fiber',
			shape: 'Elongated',
			handle_length: '5.875"',
			grip_circumference: '4.25"',
			power_rating: 9,
			control_rating: 7,
			spin_rating: 9,
			forgiveness_rating: 7,
			skill_level: ['intermediate', 'advanced'],
			description:
				'Premium power paddle with Variable Release 2.0 technology. Excellent for players seeking power with spin.',
			key_features: [
				'Variable Release 2.0 technology',
				'Raw Toray T700 carbon surface',
				'MachPro polymer core',
				'Vortex Barrier Edge technology',
			],
			best_for: ['Power with spin', 'Aggressive net play', 'All-court power'],
			pros: [
				'Excellent power and spin',
				'Quality construction',
				'Good reach',
				'Proven performance',
			],
			cons: [
				'Premium pricing',
				'Less forgiving than control paddles',
				'May be too powerful for beginners',
			],
		},
	],
	'control': [
		{
			id: 'selkirk-luxx-control',
			name: 'Selkirk LUXX Control Air',
			brand: 'Selkirk',
			price: 249.99,
			image: '/api/placeholder/300/200',
			weight: '7.8-8.1 oz',
			core_thickness: '20mm',
			surface: 'Florek Carbon Fiber',
			shape: 'Invikta (Elongated)',
			handle_length: '5.35"',
			grip_circumference: '4.25"',
			power_rating: 7,
			control_rating: 10,
			spin_rating: 8,
			forgiveness_rating: 10,
			skill_level: ['intermediate', 'advanced'],
			description:
				'Ultimate control paddle with massive sweet spot. Thermoformed construction with 20mm core for maximum forgiveness.',
			key_features: [
				'20mm X7 Thikset Honeycomb core',
				'Florek Carbon Fiber face',
				'360° Proto Molding construction',
				'Aero-DuraEdge Edgeless technology',
			],
			best_for: ['Precision placement', 'Dink battles', 'Consistent touch shots'],
			pros: [
				'Massive sweet spot',
				'Excellent control',
				'Premium feel',
				'Very forgiving',
			],
			cons: [
				'Expensive',
				'Less power than competitors',
				'May feel too controlled for power players',
			],
		},
		{
			id: 'joola-perseus-16mm',
			name: 'JOOLA Perseus Pro IV 16mm',
			brand: 'JOOLA',
			price: 199.95,
			image: '/api/placeholder/300/200',
			weight: '7.9-8.3 oz',
			core_thickness: '16mm',
			surface: 'Textured Carbon Fiber',
			shape: 'Elongated',
			handle_length: '5.5"',
			grip_circumference: '4.25"',
			power_rating: 8,
			control_rating: 9,
			spin_rating: 8,
			forgiveness_rating: 8,
			skill_level: ['intermediate', 'advanced'],
			description:
				'Balanced control version of the Perseus with 16mm core for softer feel and better touch around the net.',
			key_features: [
				'16mm Propulsion core',
				'TechFlex Power technology',
				'Textured carbon surface',
				'Enhanced dwell time',
			],
			best_for: ['All-court control', 'Touch shots', 'Balanced power and control'],
			pros: [
				'Great balance of power/control',
				'Good spin',
				'Quality construction',
				'Proven tour paddle',
			],
			cons: [
				'Still requires skill to master',
				'Premium price',
				'May lack power for some',
			],
		},
	],
	'all-court': [
		{
			id: 'paddletek-bantam-tko',
			name: 'Paddletek Bantam TKO-C',
			brand: 'Paddletek',
			price: 249.99,
			image: '/api/placeholder/300/200',
			weight: '7.8-8.2 oz',
			core_thickness: '12.7mm/14.3mm',
			surface: 'PT-700 Raw Carbon Fiber',
			shape: 'Elongated',
			handle_length: '5.25"',
			grip_circumference: '4.25"',
			power_rating: 9,
			control_rating: 8,
			spin_rating: 9,
			forgiveness_rating: 8,
			skill_level: ['intermediate', 'advanced'],
			description:
				'Designed with pro Christian Alshon for balanced power and control. Excellent for all-court play.',
			key_features: [
				'PT-700 unidirectional raw carbon',
				'Bantam PolyCore with Quick Response',
				'Two thickness options',
				'Professional design input',
			],
			best_for: [
				'All-court versatility',
				'Power with control',
				'Intermediate to advanced play',
			],
			pros: [
				'Great balance',
				'Excellent spin',
				'Durable construction',
				'Versatile performance',
			],
			cons: [
				'Premium price',
				'Slightly head-heavy',
				'May be too powerful for beginners',
			],
		},
		{
			id: 'engage-pursuit-pro-ex',
			name: 'Engage Pursuit Pro EX 6.0',
			brand: 'Engage',
			price: 207.99,
			image: '/api/placeholder/300/200',
			weight: '7.8-8.2 oz',
			core_thickness: '15.2mm',
			surface: 'Raw T700 Carbon Fiber',
			shape: 'Standard',
			handle_length: '5.875"',
			grip_circumference: '4.25"',
			power_rating: 8,
			control_rating: 8,
			spin_rating: 8,
			forgiveness_rating: 8,
			skill_level: ['intermediate', 'advanced'],
			description:
				'Balanced all-court paddle with standard shape for maximum maneuverability and consistent performance.',
			key_features: [
				'Standard shape for balance',
				'16mm MachPro core',
				'Raw carbon surface',
				'Variable Release 2.0',
			],
			best_for: [
				'Balanced gameplay',
				'All-court versatility',
				'Consistent performance',
			],
			pros: [
				'Well-balanced specs',
				'Good for multiple playing styles',
				'Quality construction',
				'Proven design',
			],
			cons: [
				'Jack of all trades approach',
				'Premium pricing',
				'May not excel in specific areas',
			],
		},
	],
	'beginner': [
		{
			id: 'selkirk-luxx-epic',
			name: 'Selkirk LUXX Control Air Epic',
			brand: 'Selkirk',
			price: 249.99,
			image: '/api/placeholder/300/200',
			weight: '7.8-8.1 oz',
			core_thickness: '20mm',
			surface: 'Florek Carbon Fiber',
			shape: 'Standard (Epic)',
			handle_length: '5.35"',
			grip_circumference: '4.25"',
			power_rating: 6,
			control_rating: 10,
			spin_rating: 7,
			forgiveness_rating: 10,
			skill_level: ['beginner', 'intermediate'],
			description:
				'Most forgiving paddle available with massive sweet spot. Standard shape provides maximum stability for developing players.',
			key_features: [
				'Massive 20mm sweet spot',
				'Standard shape for stability',
				'Thermoformed construction',
				'Premium materials',
			],
			best_for: [
				'Learning fundamentals',
				'Consistent contact',
				'Building confidence',
			],
			pros: [
				'Most forgiving',
				'Large sweet spot',
				'Premium quality',
				'Great for learning',
			],
			cons: ['Expensive for beginners', 'Less power', 'May outgrow quickly'],
		},
	],
};

export default PADDLE_DATABASE;
